## Session4 - playground2

- Import the necessary packages
- Load the iris dataset
- Create the observations `X` and labels `y`


- 必要なパッケージをインポートします
- アヤメのデータセットを読み込みます
- 観測値`X`とラベル`y`を作成します

In [127]:
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt

# Load data
iris = np.genfromtxt('iris_data.csv', delimiter=',')

X = iris[:,1:]
y = iris[:,0]
print("X has shape:", X.shape)
print("y has shape:", y.shape)

X has shape: (150, 4)
y has shape: (150,)


## TASK 1: preparation

Copy your code for data preparation from [session4-playground1](session4-playground1.ipynb) (both TASK1 and TASK2) in the cell below and execute it.

以下のセルに[session4-playground1](session4-playground1.ipynb)からデータ準備用のコード（TASK1とTASK2の両方）をコピーして、実行してください。

In [128]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test  = train_test_split(X, y, test_size=0.5)

print("Training set size:", X_train.shape[0])
print("Testing set size:", X_test.shape[0])

Training set size: 75
Testing set size: 75


In [129]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [130]:
scaler.fit(X_train);

In [131]:
# train scaling
X_train_raw = X_train 
X_train = scaler.transform(X_train_raw)

# test scaling
X_test_raw = X_test
X_test = scaler.transform(X_test_raw)

## TASK 2
- Create and train a linear support vector classifier


- 線形サポートベクトル分類器を作成し、トレーニングさせる

In [132]:
from sklearn.svm import LinearSVC
linear_SVC = LinearSVC()
linear_SVC.fit(X_train, y_train); 

## TASK 3
- Predict the labels for the test features


- テストデータのラベルを予測する

In [133]:
y_pred = linear_SVC.predict(X_test)

## TASK 4
- Show the confusion matrix
- Compute the accuracy


- 混同行列を表示する
- 精度を計算する

In [134]:
# print accuracy
from sklearn.metrics import accuracy_score
A = accuracy_score(y_test,  y_pred)
print("Accuracy: {:.02f}".format(A))

Accuracy: 0.92


In [135]:
# confusion matrix
from sklearn.metrics import confusion_matrix

CM = confusion_matrix(y_test, y_pred)
print(CM)

[[25  0  0]
 [ 0 24  4]
 [ 0  2 20]]


## OPTIONAL 1
- Run the training another time and compare (tip: you can use `Cell -> Run All` from the menu)
- Change the proportion of test samples and see the impact on the performance


- トレーニングをもう一度実行して、結果を比較します（ヒント：メニューから`Cell -> Run All`を利用できます）
- テストサンプルの比率を変更し、パフォーマンスへの影響を確認する

In [136]:
## YOUR CODE HERE
X_train, X_test, y_train, y_test  = train_test_split(X, y, test_size=0.3)

In [137]:
scaler = StandardScaler()
scaler.fit(X_train);

In [138]:
# train scaling
X_train_raw = X_train 
X_train = scaler.transform(X_train_raw)

# test scaling
X_test_raw = X_test
X_test = scaler.transform(X_test_raw)

In [139]:
linear_SVC.fit(X_train, y_train); 

In [140]:
y_pred = linear_SVC.predict(X_test)

In [141]:
linear_SVC = LinearSVC()
linear_SVC.fit(X_train, y_train); 

In [142]:
# print accuracy
from sklearn.metrics import accuracy_score
A = accuracy_score(y_test,  y_pred)
print("Accuracy: {:.02f}".format(A))

Accuracy: 0.93


In [143]:
# confusion matrix
CM = confusion_matrix(y_test, y_pred)
print(CM)

[[15  0  0]
 [ 0 12  1]
 [ 0  2 15]]


## OPTIONAL 2

The splitting between training and testing set does not care if there is an "equal" number of each flower type in the sets.

- Write some code to split the dataset randomly and care about having an equal representation of each flower type (you can start from the code for manually spliting in the main notebook)
- Test the average performance of the classifier using this dataset splitting method

トレーニングセットとテストセットの分割は、セット内の各花の種類が「等しい」数であるかどうかを考慮していません。

- データセットをランダムに分割し、各花の種類の数が同じになるためのコードを実装してください（ヒント：メインのノートブックにある手動の分割のコードを元に開発できます）
- このデータセット分割方法を使用して、分類器の平均パフォーマンスを確認してください

In [144]:
def my_train_test_split(x, y, testing_ratio):
    print(y)
    a_index = np.where(y==0)
    a_x = x[a_index]
    a_y = y[a_index]
    
    b_index = np.where(y==1)
    b_x = x[b_index]
    b_y = y[b_index]
    
    c_index = np.where(y==2)
    c_x = x[c_index]
    c_y = y[c_index]

    xs = [a_x, b_x, c_x]
    ys = [a_y, b_y, c_y]

    a_x_train, a_x_test, a_y_train, a_y_test = create_test_train(xs[0], ys[0], testing_ratio)
    b_x_train, b_x_test, b_y_train, b_y_test = create_test_train(xs[1], ys[1], testing_ratio)
    c_x_train, c_x_test, c_y_train, c_y_test = create_test_train(xs[2], ys[2], testing_ratio)

    x_train = np.concatenate([a_x_train, b_x_train, c_x_train], axis=0)
    x_test = np.concatenate([a_x_test, b_x_test, c_x_test], axis=0)
    y_train = np.concatenate([a_y_train, b_y_train, c_y_train], axis=0)
    y_test = np.concatenate([a_y_test, b_y_test, c_y_test], axis=0)

    return x_train, x_test,  y_train, y_test
    
        
def create_test_train(x, y, testing_ratio):
    number_samples = x.shape[0]
    shuffle_index = np.random.permutation(number_samples)
    x = x[shuffle_index]
    y = y[shuffle_index]
    test_samples = int(testing_ratio*number_samples)

    x_test = x[:test_samples]
    y_test = y[:test_samples]

    x_train = x[test_samples:]
    y_train = y[test_samples:]

    return x_train, x_test, y_train, y_test

In [145]:
X_train, X_test, y_train, y_test  = my_train_test_split(X, y, 0.3)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2.]


In [146]:
scaler = StandardScaler()
scaler.fit(X_train);

In [147]:
# train scaling
X_train_raw = X_train 
X_train = scaler.transform(X_train_raw)

# test scaling
X_test_raw = X_test
X_test = scaler.transform(X_test_raw)

In [148]:
linear_SVC.fit(X_train, y_train); 

In [149]:
y_pred = linear_SVC.predict(X_test)

In [150]:
linear_SVC = LinearSVC()
linear_SVC.fit(X_train, y_train); 

In [151]:
A = np.sum(np.diag(CM)) / np.sum(CM)
print("Accuracy: {:.02f}".format(A))

Accuracy: 0.93


In [152]:
# confusion matrix
CM = confusion_matrix(y_test, y_pred)
print(CM)

[[15  0  0]
 [ 0 15  0]
 [ 0  2 13]]


In [153]:
P = np.diag(CM) / np.sum(CM, axis = 0)
R = np.diag(CM) / np.sum(CM, axis = 1)
F = 2.0 * R * P / (R + P) # 1 / ((1/P + 1/R) / 2 ) = 2 * R * P / (R + P)
for i in range(3):
    print("Class '{}' : P = {:.02f} R = {:.02f}  F = {:.02f}".format(i, P[i], R[i], F[i]))

Class '0' : P = 1.00 R = 1.00  F = 1.00
Class '1' : P = 0.88 R = 1.00  F = 0.94
Class '2' : P = 1.00 R = 0.87  F = 0.93
